# Generated by Django 5.1.5 on 2025-02-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalname',
            old_name='pdf_file',
            new_name='journal_template_file',
        ),
        migrations.RenameField(
            model_name='journalname',
            old_name='word_file',
            new_name='stylesheet_file',
        ),
    ]
