# Generated by Django 5.1.5 on 2025-02-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_journal_template_file_journalname_journal_template_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='journal_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.issue'),
        ),
    ]
