# Generated by Django 5.1.5 on 2025-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_paper_journal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='journal_name',
            new_name='journal_issue_number',
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
